/// Flutter icons LogOutIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LogOutIcon
///      fonts:
///       - asset: fonts/LogOutIcon.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class LogOutIcon {
  LogOutIcon._();

  static const _kFontFam = 'LogOutIcon';

  static const IconData logout = IconData(0xf02d, fontFamily: _kFontFam);
}
